"""add nick and age to the users

Revision ID: 15ec6ec2be71
Revises: 018837d57806
Create Date: 2025-09-06 14:00:43.823075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15ec6ec2be71"
down_revision: Union[str, Sequence[str], None] = "018837d57806"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("nickname", sa.String(length=25), nullable=False))
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age")
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###
